version: '3.9'

services:
  front:
    container_name: gdp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - networkgdp

networks:
  networkgdp:
    driver: bridge
