version: '3.9'
services:
    angular-app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '4200:4200'
        volumes:
            - ./src:/app/src
        depends_on:
            - api

    api:
        image: gdp-back-api
